<?php
$class = "";
// @codingStandardsIgnoreFile
if ($block->getVoucherActive()) {
    if (!empty($block->getVoucherAmountUsed())) {
        $class = "applied";
    } ?>
    <div class="voucher block" id="block-giftcard"
         data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
        <div class="title" data-role="title">
            <strong id="block-giftcard-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */
                __('Apply Voucher') ?></strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-giftcard-heading">
            <form id="voucher-form"
                  action="<?= /* @escapeNotVerified */
                  // controller
                  $block->getUrl('omni/cart/VoucherUsed') ?>"
                  method="post" 
                  data-mage-init='{"giftCard":{"GiftcardSelector": "#removevoucher",
                                               "removevoucherSelector": "#removevoucher",
                                               "applyVoucherButton": "input.action.applyVoucher",
                                               "cancelVoucherButton": "input.action.cancelVoucher"}}'>
                <div class="fieldset <?php echo $class ?>">
                    <input type="hidden" name="removegiftcard" id="removegiftcard" value="0"/>
                    <div class="field voucher-code-field">
                        <div class="control">
                            <input type="text" class="input-text" id="voucherno" name="voucherno"
                                   placeholder="Enter Voucher Code" value="<?= $block->getVoucherNo() ?>"
                                   required="required"/>
                        </div>
                    </div>
                    <div class="field voucher-amount-field">
                        <div class="control">
                            <input type="number" min="0" class="input-text" id="voucheramount" name="voucheramount"
                                   placeholder="Amount to Use" value="<?= $block->getVoucherAmountUsed() ?>"
                                   required="required"/>
                        </div>
                    </div>
                    <div class="actions actions-toolbar">
                        <div class="primary">
                            <?php if (empty($block->getVoucherAmountUsed())): ?>
                                <input class="action applyvoucher primary" type="submit"
                                       value="<?= __('Apply') ?>"></input>
                            <?php else: ?>
                                <input class="action applyvoucher primary" type="submit"
                                       value="<?= __('Update') ?>"></input>
                                <input type="submit" class="action cancelvoucher primary"
                                       value="<?= __('Cancel') ?>"></input>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
<?php
} ?>